server:
  port: 8080

spring:
  application:
    name: kotlin-springboot-service



#######################
# Debugging ( logger level)
#######################

logging:
  level:
    root: INFO
    com.jeonguk.web: DEBUG
    org.springframework.web: DEBUG